Repository GSG-G11/Top-Headlines, pull requests merged in 2022-02, with the labels that each got.

#2 1 install dep
  .eslintrc.json
  .gitattributes
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
Labels: Awaiting Review

#4 add file structure
  public/css/style.css
  public/html/404.html
  public/html/500.html
  public/index.html
  public/js/index.js
  src/app.js
  src/controllers/index.js
  src/index.js
  src/routes/index.js
  src/test.js
Labels: Awaiting Review

#6 add index.js and app.js
  package.json
  src/app.js
  src/index.js
Labels: Awaiting Review

#10 general page function
  .vscode/settings.json
  src/controllers/error.js
  src/controllers/generalPage.js
  src/controllers/index.js
Labels: Awaiting Review

#12 create main routes
  package-lock.json
  package.json
  src/app.js
  src/controllers/generalPage.js
  src/controllers/getCategory.js
  src/controllers/handleBusiness.js
  src/controllers/handleEntertainment.js
  src/controllers/handleGeneral.js
  src/controllers/handleHealth.js
  src/controllers/handleScience.js
  src/controllers/handleSearch.js
  src/controllers/handleSports.js
  src/controllers/handleTechnology.js
  src/controllers/index.js
  src/index.js
  src/routes/category/index.js
  src/routes/index.js
Labels: Awaiting Review

#14 add 404.html, 500.html, images folder, favicon.ico
  public/favicon.ico
  public/html/404.html
  public/html/500.html
  public/images/error.png
Labels: Approved

#16 add handle search
  package.json
  src/controllers/getCategory.js
  src/controllers/handleSearch.js
Labels: Approved

#18 add public
  public/css/category.css
  public/css/content.css
  public/css/home.css
  public/css/search.css
  public/css/style.css
  public/html/category.html
  public/html/search.html
  public/js/index.js
Labels: Awaiting Review

#20 19 front end fetch+dom
  public/css/content.css
  public/css/style.css
  public/html/category.html
  public/html/search.html
  public/images/news-img.jpg
  public/images/news.png
  public/index.html
  public/js/category.js
  public/js/index.js
  public/js/search.js
Labels: Awaiting Review

#22 add test.js file
  src/test.js
Labels: Awaiting Review

#24 add readme
  README.md
Labels: To Do

#28 handle no result value
  public/images/no-result.jpg
  public/js/index.js
Labels: Done

#30 add some routes tests
  src/test.js
Labels: Done

#37 handle errors + api daily limit
  public/css/error.css
  public/html/404.html
  public/html/500.html
  public/images/503.jpg
  public/js/index.js
Labels: Done

#38 refactoring categories routes
  src/controllers/getCategory.js
  src/controllers/handleBusiness.js
  src/controllers/handleEntertainment.js
  src/controllers/handleGeneral.js
  src/controllers/handleHealth.js
  src/controllers/handleScience.js
  src/controllers/handleSports.js
  src/controllers/handleTechnology.js
  src/controllers/index.js
  src/routes/category/index.js
  src/routes/index.js
Labels: Awaiting Review
